services:
  db:
    image: mysql:8.2.0
    command: "--default-authentication-plugin=mysql_native_password"
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3307:3307
    networks:
      - private
    environment:
      - MYSQL_DATABASE=flexixdb
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - public
      - private
    depends_on:
      - db

  # app_golang:
  #   build:
  #     context: app_golang
  #     target: builder
  #   secrets:
  #     - db-password
  #   depends_on:
  #     - db

  # proxy:
  #   image: nginx
  #   volumes:
  #     - type: bind
  #       source: ./proxy/nginx.conf
  #       target: /etc/nginx/conf.d/default.conf
  #       read_only: true
  #   ports:
  #     - 80:80
  #   networks:
  #     - public
  #     - private
  #   depends_on:
  #     - db

networks:
  public:
  private:

volumes:
  db-data:

secrets:
  db-password:
    file: ./db/password.txt
