# Generated by Django 3.2.13 on 2023-12-15 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Fname', models.CharField(max_length=255)),
                ('Lname', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=255, unique=True)),
                ('Pass', models.CharField(max_length=255)),
            ],
        ),
    ]
